# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('album', models.CharField(max_length=100, null=True)),
                ('artistLocation', models.CharField(max_length=100, null=True)),
                ('artistName', models.CharField(max_length=100, null=True)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('keySignature', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('popularity', models.DecimalField(decimal_places=7, max_digits=20, null=True)),
                ('timeSignature', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('year', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('artistFamiliarity', models.DecimalField(decimal_places=7, max_digits=20, null=True)),
                ('artistPopularity', models.DecimalField(decimal_places=7, max_digits=20, null=True)),
                ('oneStarArtistPopularity', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('twoStarArtistPopularity', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('threeStarArtistPopularity', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('fourStarArtistPopularity', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('fiveStarArtistPopularity', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryRapHipHopRnb', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryRock', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryFolkCeltic', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryElectronicTrance', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryMetal', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryPunkGrungeSka', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryPopChart', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryJazzBlues', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryCountry', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categorySoulReggaeFunk', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('categoryDance', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
            ],
        ),
    ]
